### ISSUE TITLE
Bad UART baudrate configuration

### ISSUE THREAD

**Issue by FoujanetG** [LairdCP/Lyra_Firmware#2]
Hi,

Using:
-Laird Lyra-P devKit [RS link ](https://fr.rs-online.com/web/p/modules-de-developpement-de-communication-et-sans-fil/2460517?cm_mmc=FR-PLA-DS3A-_-google-_-CSS_FR_FR_Raspberry_Pi_%26_Arduino_%26_Outils_de_developpement_Whoop-_-(FR:Whoop!)+Modules+de+d%C3%A9veloppement+de+communication+et+sans+fil-_-2460517&matchtype=&aud-827186183926:pla-337541965362&gclid=Cj0KCQjwj7CZBhDHARIsAPPWv3d5wkRU83kM57QS89cpOhD-DIhe2UAHkERsB-gvY5ZTV8xdflVYFa4aAksKEALw_wcB&gclsrc=aw.ds)
-In BGx Command (switch button on Bgx (on the left))
-flashing by Serial DFU (UART), with the process of User Guide - Firmware Options and Upgrading - Lyra Series v1_2.pdf 
-flash the bootloader _LYRA-P_Bluetooth_Xpress_Bootloader_480-00207-R126.0.0.4.hex_ (or _LYRA-P_Bootloader_480-00184-R126.1.0.3.hex_, it's the same issue) and _LYRA-P_Bluetooth_Xpress.hex_

I can communicate with the device.
For example I can send `get ua b` ==> 115200
Now I want to set the uart to 2Mbauds ==> `set ua b 2000000`, and save the configuration `save`
I power off / on the device
==> I cannot communicate with the device with my terminal. 

I reflash the .hex files to have the baudrate by default (115200).
I check with other baudrate values (as 256000), the issue is the same.

I need to configure the baudrate to have the best performance on the link to use the BLe bandwith at the maximum.

Firmware flashed are the good for my needs?
Is there a bug on the FW?
for information, If i do the same thing with the BGX dev kit of silab, it works.

thanks

**Comment by claplante88** [comment]
Hi,

The Lyra EVK has a built in a Virtual Com Port (VCOM) that provides USB to Serial conversion between a PC connected over USB and the UART port on the Lyra’s EFR32BG22 MCU. The DVK’s default UART rate out of the box is 115200. For applications that require either faster or slower speeds on the UART, the rate must be changed on both the EFR32BG22 and the VCOM port. This can be done using the console within Simplicity Studio.

With your PC’s USB connected to the USB port on the EVK open Simplicity Studio and launch the console as shown below.

![image](https://user-images.githubusercontent.com/95433717/192873945-0049e502-7a35-4ba3-8f54-44b36a7296cd.png)

Select Serial 1 and press Enter. The Wireless Xpress console will respond with Ready.

![image](https://user-images.githubusercontent.com/95433717/192874059-d11f2bb7-a7af-454a-b9bb-69e2c0a748fb.png)

To change the rate on the EFR32BG22 UART type the command:

Set ua b <new rate>
Commit the change by typing command:
Save
The new rate can be read back for verification via command:
Get ua b

![image](https://user-images.githubusercontent.com/95433717/192874261-b9273737-c6e3-41fd-a27a-17ed792858a1.png)

Next, change the baud rate of the VCOM. In the console window select the admin tab, and then press Enter.

![image](https://user-images.githubusercontent.com/95433717/192874333-b95664f1-d760-45c3-ac0f-c29bfd1f6aee.png)

Change the rate by typing the command:

Serial vcom config speed <new rate>
The new rate and all other UART parameters can be read via the following command:
Serial vcom

![image](https://user-images.githubusercontent.com/95433717/192874420-3d8bb677-33b2-4352-b4f3-82266acb50e1.png)

Switch back to Serial 1 console tab and press the reset button on the EVK. You should now be able to use the serial port at the newly configured rate (In this case, 2Mb).

![image](https://user-images.githubusercontent.com/95433717/192874481-5f6bc8d3-8e94-4498-bce3-eb801dddd889.png)

**Comment by FlorianBaumgartl-Ezurio** [comment]
Hi @FoujanetG − We have not heard back from you and I was wondering if you were able to resolve the issue with the information Chris provided to you? I would also like to inform you that we've published in the meantime an application note explaining how to change the baud rate when getting started with our Lyra DVKs. You can find further information [here](https://www.lairdconnect.com/documentation/application-note-configuring-lyra-evk-uart-baud-rate) and this document covers both Bluetooth Xpress and AT Interface software options in regard to the baud rate modification.

Thanks,
Florian.

**Comment by FoujanetG** [comment]
Hi, sorry for my very late answer!

We have tried your proposal as soon as we received it, and it work
perfectly.
thank you, and thank for the new user guide link.

guillaume

**Comment by FoujanetG** [comment]
Hi, sorry for my very late answer!

We have tried your proposal as soon as we received it, and it work perfectly.
thank you, and thank for the new user guide link.

guillaume
